server:
  port: 8000
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      first:
        url: jdbc:mysql://81.70.205.10:3306/test1?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456
      second:
        url: jdbc:mysql://81.70.205.10:3306/test2?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456
      third:
        url: jdbc:mysql://81.70.205.10:3306/test3?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456
      fourth:  #蜜步数据源从库
        #url: jdbc:mysql://39.107.253.206:3306/test3?characterEncoding=utf8&useSLL=false&serverTimezone=UTC
        #username: root
        #password: rPCyKmOOQ1jpEG3h
        #宋爸爸专用数据源，闲杂人等不要乱动
        url: jdbc:mysql://81.70.205.10:3306/test3?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456
        #url: jdbc:mysql://10.1.11.110:3310/baojia_bike?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        #username: baojia_xm
        #password: DgisNKhg
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxWait: 10000
        timeBetweenEvictionRunsMillis: 600000
        minEvictableIdleTimeMillis: 1800000
        removeAbandonedTimeout: 180
        validationQuery: SELECT 1
        removeAbandoned: true
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    host: 81.70.205.10
    port: 6379
    password: 123456
    #    database: 2
    timeout: 30s
logging:
  config: classpath:logback-dev.xml
