server:
  port: 8090
spring:
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
  servlet:
      multipart:
          max-file-size: 100MB
          max-request-size: 100MB
          enabled: true
  profiles:
    active: @profiles.active@
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.entity
  #字段驼峰转换
  db-column-underline: true
  #刷新mapper 调试神器
  refresh-mapper: false
